import { Footer, Header, TopMenu } from "@/components";
import { geistMono, geistSans } from "@/ui"
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-[#1f1f47]`}
      >
        <TopMenu />
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
